# Generated by Django 2.2.4 on 2019-08-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='aliments',
            field=models.ManyToManyField(blank=True, related_name='profil_set', to='aliments.Aliment'),
        ),
    ]
