language: python
python:
  - 3.6

env:
  - DJANGO=2.2

services:
  - postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=purbeurre.settings
  - export ADMIN=fred1599

install:
  - pip install -r requirements.txt
  - pip install django --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c 'create database fred;' -U postgres

script:
  - python manage.py migrate

