language: python
python:
  - 3.6

env:
  - DJANGO=2.2

before_install:
  - export DJANGO_SETTINGS_MODULE=purbeurre.settings

install:
  - pip install -r requirements.txt
  - pip install django --quiet
  - pip install psycopg2 --quiet

script:
  - python manage.py migrate
