language: python
matrix:
  include:
    - python: 3.6
    dist: xenial
    sudo: true
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
virtualenv:
  system_site_packages: true
