# Generated by Django 2.2.4 on 2019-09-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0003_auto_20190902_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='url',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='url_image',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
