# Generated by Django 2.2.4 on 2019-08-24 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('substitute_of', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('url_image', models.URLField(blank=True)),
                ('score', models.CharField(blank=True, max_length=1)),
                ('users', models.ManyToManyField(related_name='aliment', to=settings.AUTH_USER_MODEL, verbose_name='liste des utilisateurs')),
            ],
        ),
    ]
