# Generated by Django 2.2.4 on 2019-09-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0002_favoris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
